name: shell-commands
on: push
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "Hello"
      - name: echo multi-line
        run: |
          pwd
          node -v
          ls -a
