name: terraform-stuff
on: push
jobs:
  run-terraform-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform-version: 1.1.9
      - name: terraform init
        run: terraform init
